name: tmda
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.3.3
  flutter_animate: ^4.2.0+1
  hive_flutter: ^1.1.0
  get_it: ^7.6.4
  dartz: ^0.10.1
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  url_launcher: ^6.2.1
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  auto_route: ^7.8.4
  bloc_concurrency: ^0.2.2
  lottie: ^2.7.0
  injectable: ^2.3.2
  intl: ^0.18.1
  rxdart: ^0.27.7
  flutter_cache_manager: ^3.3.1
  flutter_lazy_indexed_stack: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  auto_route_generator: ^7.3.2
  injectable_generator: 
  build_runner: ^2.4.6
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: SolarSystem
      fonts:
        - asset: assets/fonts/SolarSystem.ttf